-- 원격 DB 에만 있던 마이그레이션을 복원한 것.
-- 2026-09-28~30 에 저장소를 거치지 않고 적용돼(대시보드 SQL 편집기로 보인다)
-- supabase_migrations.schema_migrations 에만 기록돼 있었다. 그 statements 를
-- 그대로 옮겨 적는다 —— 내용을 손대지 않는다. 이력과 파일을 맞추는 것이 목적이다.

create table if not exists public.customs_classification_evidence (
  id bigint generated by default as identity primary key,
  market text not null check (market in ('EU')),
  cn_code text not null check (cn_code ~ '^[0-9]{4,10}$'),
  source_type text not null check (source_type in ('CLASS','EBTI','CN_EXPLANATORY_NOTE','CLASSIFICATION_REGULATION','CCC_CONCLUSION','CJEU')),
  source_id text,
  title text not null,
  product_description text,
  decision_summary text,
  legal_basis text,
  decision_date date,
  valid_from date,
  valid_to date,
  source_url text not null,
  source_version text,
  source_hash text,
  is_active boolean not null default true,
  ingested_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique (source_type, source_id)
);
create index if not exists customs_classification_evidence_cn_code_idx on public.customs_classification_evidence (cn_code);
create index if not exists customs_classification_evidence_source_type_idx on public.customs_classification_evidence (source_type);
alter table public.customs_classification_evidence enable row level security;
grant select on public.customs_classification_evidence to anon, authenticated;
create policy "classification evidence is publicly readable"
on public.customs_classification_evidence for select
to anon, authenticated
using (is_active = true);
