-- 원격 DB 에만 있던 마이그레이션을 복원한 것.
-- 2026-09-28~30 에 저장소를 거치지 않고 적용돼(대시보드 SQL 편집기로 보인다)
-- supabase_migrations.schema_migrations 에만 기록돼 있었다. 그 statements 를
-- 그대로 옮겨 적는다 —— 내용을 손대지 않는다. 이력과 파일을 맞추는 것이 목적이다.

create table if not exists public.eu_customs_measures (
 id bigint generated by default as identity primary key,
 cn_code text not null check (cn_code ~ '^[0-9]{4,10}$'),
 origin_country text,
 destination_country text,
 measure_type text not null check (measure_type in ('THIRD_COUNTRY_DUTY','PREFERENCE','VAT','REQUIREMENT','REGULATION')),
 rate_percent numeric,
 rate_text text,
 title text not null,
 detail text,
 legal_basis text,
 source_url text not null,
 valid_from date,
 valid_to date,
 is_active boolean not null default true,
 metadata jsonb not null default '{}'::jsonb,
 ingested_at timestamptz not null default now()
);
create index if not exists eu_customs_measures_lookup_idx on public.eu_customs_measures(cn_code,origin_country,destination_country,measure_type,is_active);
alter table public.eu_customs_measures enable row level security;
grant select on public.eu_customs_measures to anon, authenticated;
create policy "eu customs measures public read" on public.eu_customs_measures for select to anon,authenticated using (is_active=true);
